#!/bin/bash

echo "🔐 AWS SSO Configuration"
echo "========================"
echo ""
echo "✅ SSO Start URL: https://d-9667754ecf.awsapps.com/start"
echo "✅ Region: us-east-1"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1️⃣ Run this command:"
echo ""
echo "   aws configure sso"
echo ""
echo "2️⃣ When prompted, enter:"
echo "   - SSO session name: my-sso"
echo "   - SSO start URL: https://d-9667754ecf.awsapps.com/start"
echo "   - SSO region: us-east-1"
echo "   - SSO registration scopes: [press Enter]"
echo ""
echo "3️⃣ Browser will open → Login to AWS SSO"
echo ""
echo "4️⃣ Select:"
echo "   - AWS Account (your account will be shown)"
echo "   - IAM Role (e.g., AdministratorAccess)"
echo "   - CLI default region: us-east-1"
echo "   - CLI output format: json"
echo "   - Profile name: default"
echo ""
echo "5️⃣ Test connection:"
echo "   aws sts get-caller-identity --profile default"
echo ""
echo "6️⃣ Use with IAM MCP Server:"
echo "   export AWS_PROFILE=default"
echo "   awslabs.iam-mcp-server --readonly"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  Note: This must be run in an interactive terminal"
echo "    (not through automation)"
echo ""
