#!/bin/bash

echo "🔐 AWS SSO Setup Helper"
echo "======================="
echo ""
echo "Copy and paste these commands ONE BY ONE:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Start SSO configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "aws configure sso"
echo ""
echo "When prompted, copy/paste these answers:"
echo ""
echo "  SSO session name [my-sso]: my-sso"
echo "  SSO start URL [None]: https://d-9667754ecf.awsapps.com/start"
echo "  SSO region [None]: us-east-1"
echo "  SSO registration scopes [sso:account:access]: [just press Enter]"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Browser will open"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  → Login with your AWS SSO credentials"
echo "  → Click 'Allow' to authorize AWS CLI"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Select account and role"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  → Choose your AWS account"
echo "  → Choose a role (e.g., AdministratorAccess)"
echo ""
echo "Then enter:"
echo "  CLI default client Region [None]: us-east-1"
echo "  CLI default output format [None]: json"
echo "  CLI profile name [default]: default"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Test connection"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "aws sts get-caller-identity --profile default"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: Use with IAM MCP Server"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "export AWS_PROFILE=default"
echo "awslabs.iam-mcp-server --readonly"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  If browser doesn't open automatically:"
echo "    aws configure sso --no-browser"
echo "    Then copy the URL and open in browser manually"
echo ""
